#!/usr/bin/env bash
# === Portfolio Scripts Global Access Setup ===
# Makes all portfolio scripts and aliases available from anywhere

set -euo pipefail

PORTFOLIO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPTS_DIR="$PORTFOLIO_ROOT/scripts"

echo "🔧 Setting up global access to portfolio scripts..."
echo "📁 Portfolio root: $PORTFOLIO_ROOT"

# Create ~/.local/bin if it doesn't exist (standard user bin directory)
LOCAL_BIN="$HOME/.local/bin"
mkdir -p "$LOCAL_BIN"

# Create wrapper scripts for each portfolio script
create_wrapper() {
    local script_name="$1"
    local wrapper_name="$2"
    local wrapper_path="$LOCAL_BIN/$wrapper_name"

    cat > "$wrapper_path" << EOF
#!/usr/bin/env bash
# Auto-generated wrapper for portfolio script: $script_name
PORTFOLIO_ROOT="$PORTFOLIO_ROOT"
cd "\$PORTFOLIO_ROOT"
exec "\$PORTFOLIO_ROOT/scripts/$script_name" "\$@"
EOF
    chmod +x "$wrapper_path"
    echo "✅ Created: $wrapper_name → $script_name"
}

# Create Python script wrappers that activate venv
create_python_wrapper() {
    local script_name="$1"
    local wrapper_name="$2"
    local wrapper_path="$LOCAL_BIN/$wrapper_name"

    cat > "$wrapper_path" << EOF
#!/usr/bin/env bash
# Auto-generated wrapper for portfolio Python script: $script_name
PORTFOLIO_ROOT="$PORTFOLIO_ROOT"
cd "\$PORTFOLIO_ROOT"
source "\$PORTFOLIO_ROOT/.venv/bin/activate" 2>/dev/null || {
    echo "⚠️  Portfolio venv not found, using system Python"
}
exec python "\$PORTFOLIO_ROOT/scripts/$script_name" "\$@"
EOF
    chmod +x "$wrapper_path"
    echo "✅ Created: $wrapper_name → $script_name (with venv)"
}

# Create wrappers for all scripts
echo ""
echo "📝 Creating global command wrappers..."

# Main interactive scripts
create_wrapper "jn" "jn"
create_wrapper "new_notebook.sh" "newnb"
create_wrapper "export_notebooks_menu.sh" "exportnb"
create_wrapper "export_figures_menu.sh" "exportfigs"

# Python utilities (with venv activation)
create_python_wrapper "export_notebooks.py" "exportnb-direct"
create_python_wrapper "export_figures.py" "exportfigs-direct"

echo ""
echo "🔗 Adding portfolio functions to ~/.bashrc..."

# Create bashrc additions
BASHRC_ADDITIONS=$(cat << 'EOF'

# === Portfolio Global Access ===
# Auto-generated by setup_global_access.sh

# Add ~/.local/bin to PATH if not already there
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# Portfolio environment variable (for scripts that need it)
export PORTFOLIO_ROOT="PORTFOLIO_ROOT_PLACEHOLDER"

# Convenience aliases
alias portfolio='cd "$PORTFOLIO_ROOT"'
alias nb='newnb'  # Short alias for new notebook
alias jup='jn'    # Alternative to jn

# Portfolio utility functions
portfolio_status() {
    echo "📁 Portfolio root: $PORTFOLIO_ROOT"
    echo "🔧 Available commands:"
    echo "  jn, jup          - Launch Jupyter with case study selection"
    echo "  newnb, nb        - Create new professional notebook"
    echo "  exportnb         - Export notebooks menu"
    echo "  exportfigs       - Export figures menu"
    echo "  exportnb-direct  - Direct notebook export (no menu)"
    echo "  exportfigs-direct - Direct figure export (no menu)"
    echo "  portfolio        - cd to portfolio directory"
}

# Quick portfolio navigation
alias pf='portfolio'
alias pfs='portfolio_status'

EOF
)

# Replace placeholder with actual portfolio root
BASHRC_ADDITIONS="${BASHRC_ADDITIONS//PORTFOLIO_ROOT_PLACEHOLDER/$PORTFOLIO_ROOT}"

# Check if already added to avoid duplicates
if ! grep -q "Portfolio Global Access" ~/.bashrc; then
    echo "$BASHRC_ADDITIONS" >> ~/.bashrc
    echo "✅ Added portfolio functions to ~/.bashrc"
else
    echo "ℹ️  Portfolio functions already exist in ~/.bashrc"
fi

echo ""
echo "🎉 Global access setup complete!"
echo ""
echo "📋 Available commands from anywhere:"
echo "  jn, jup          - Launch Jupyter with case study selection"
echo "  newnb, nb        - Create new professional notebook"
echo "  exportnb         - Export notebooks menu"
echo "  exportfigs       - Export figures menu"
echo "  portfolio, pf    - Navigate to portfolio directory"
echo "  pfs              - Show portfolio status and commands"
echo ""
echo "🔄 To activate immediately, run: source ~/.bashrc"
echo "   Or open a new terminal"